version: '3.7'

services:
  backend:
    image: "mkosc/jobs"
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      spring.datasource.url: "jdbc:mysql://database:3306/jobs_db"
  database:
    image: "mysql"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: jobs_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

volumes:
  db_data: {}